### ISSUE TITLE
"Replace all" does not work as it should.

### ISSUE THREAD

**Issue by wilbdhm** [gcfbn/NotepadClone#2]
![image](https://user-images.githubusercontent.com/47501814/63624881-2daa2080-c5fe-11e9-9091-4065831c9f1d.png)
![image](https://user-images.githubusercontent.com/47501814/63624899-3c90d300-c5fe-11e9-825a-45d7dbf8531b.png)
(By the way, it should be _Replaced 2 occurrences_ and not _Replaced 2 occurrings_.)

**Comment by gcfbn** [comment]
![1](https://user-images.githubusercontent.com/43823631/63690881-0b86ed00-c80e-11e9-9006-a7a83470dc1a.png)
![2](https://user-images.githubusercontent.com/43823631/63690883-0b86ed00-c80e-11e9-8597-90027b9e8b37.png)

Fixed in https://github.com/gcfbn/NotepadClone/commit/d2a267b52ce59a730d8704af124e2f647ba6a728

As I can see, there is still something wrong with the form - the buttons are too short. Is that because you use other resolution than me or the problem is somewhere else?

**Comment by wilbdhm** [comment]
> Is that because you use other resolution

My resolution is 1440x900 FYI.

**Comment by gcfbn** [comment]
I use 1920x1080, so that's the reason.
